# Generated by Django 3.1.6 on 2021-02-07 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hoodApp', '0002_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('pic', models.ImageField(upload_to='pictures/')),
                ('contacts', models.CharField(max_length=40, null=True)),
                ('description', models.CharField(max_length=200, null=True)),
                ('neighborhood', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hoodApp.neighborhood')),
            ],
        ),
    ]
