# Generated by Django 3.1.6 on 2021-02-08 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hoodApp', '0005_auto_20210207_2241'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Hospital',
        ),
    ]
